# Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

# Firebase
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**

# Play Core (deferred components referenced by the Flutter engine)
-dontwarn com.google.android.play.core.**

# Hive generated type adapters
-keep class **$*TypeAdapter { *; }

# Keep model classes generated by json_serializable / freezed
-keepclassmembers class * {
    @com.google.gson.annotations.SerializedName <fields>;
}
-keepattributes *Annotation*, InnerClasses, Signature, Exceptions
